- name: Setup GitHub Actions Runner on runner
  hosts: compi

  vars_prompt:
    - name: "github_token"
      prompt: "Enter GitHub runner token"
      private: yes
    - name: "target_ip"
      prompt: "Enter the IP address of the Target Raspberry Pi"
      private: no
    - name: "target_pass"
      prompt: "Enter the password for the 'drone' user on the Target Pi"
      private: yes

  pre_tasks:
    - name: Ensure SSH key exists locally
      stat:
        path: "/home/compi/.ssh/id_rsa.pub"
      delegate_to: compi
      register: ssh_key

    - name: Ensure ~/.ssh directory exists
      stat:
        path: "/home/compi/.ssh"
      delegate_to: compi
      register: ssh_dir
 
    - name: Generate SSH key pair using openssh_keypair
      community.crypto.openssh_keypair:
        path: "/home/compi/.ssh/id_rsa"
        type: rsa
        size: 4096
      delegate_to: compi
      when: not ssh_key.stat.exists

    - name: Add target host to known_hosts on runner
      shell: |
        ssh-keyscan -H {{ target_ip }} >> /home/compi/.ssh/known_hosts
      delegate_to: compi

    - name: Copy SSH key to target
      delegate_to: compi
      expect:
        command: ssh-copy-id -f -i /home/compi/.ssh/id_rsa.pub drone@{{ target_ip }}
        responses:
          "Are you sure you want to continue connecting.*": "yes"
          "password:": "{{ target_pass }}"  

  roles:
    - github_runner