- name: Setup GitHub Actions Runner on runner
  hosts: compi
  become: yes

  vars_prompt:
    - name: "github_token"
      prompt: "Enter GitHub runner token"
      private: yes

  roles:
    - github_runner