- name: Ensure required packages are installed
  apt:
    name: [curl, unzip, git, nano, htop, net-tools, software-properties-common, python3-pip, python3-venv, ansible]
    state: present
    update_cache: yes

- name: Create actions-runner directory
  file:
    path: /home/compi/actions-runner
    state: directory
    owner: compi
    group: compi
    mode: '0755'

- name: Download GitHub Actions Runner
  become_user: compi
  get_url:
    url: https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-arm64-2.323.0.tar.gz
    dest: /home/compi/actions-runner/actions-runner.tar.gz

- name: Extract Runner
  become_user: compi
  unarchive:
    src: /home/compi/actions-runner/actions-runner.tar.gz
    dest: /home/compi/actions-runner
    remote_src: yes

- name: Configure GitHub Actions Runner
  become_user: compi
  command: >
    ./config.sh 
    --url https://github.com/AlZi-88/droneComPi-setup 
    --token AQBZJZ3RNZSCQ4UEBLCHRN3IAY4NE
    --name compi
    --labels raspi, infra, arm64
    --unattended
  args:
    chdir: /home/compi/actions-runner
    creates: /home/compi/actions-runner/.runner

- name: Install GitHub Actions Runner as a service
  become: yes
  command: ./svc.sh install
  args:
    chdir: /home/compi/actions-runner

- name: Start GitHub Actions Runner service
  become: yes
  command: ./svc.sh start
  args:
    chdir: /home/compi/actions-runner